### ISSUE TITLE
PHPv8js vs Hypernova

### ISSUE THREAD

**Issue by aftabnaveed** [wayfair/hypernova-php#14]
I know you mentioned that phpv8js may not be ready for production, but since it is an in-memory solution don't you think it would be faster than Hypernova?  Did you do any benchmarks to compare both?

**Comment by roippi** [comment]
I don't offhand, I can see if I can dig up anything from that project.

Let me drop some bulletpoints, kind of freeform-thought style:

- Hypernova communicates via HTTP over localhost (usually).  I've measured this request overhead at <1ms.
- The "in memory" benefit comes up with serialization costs at both ends of the request (props/ HTML).  I've measured this at around 5-10ms, total, for a large page with a ton of props and resulting markup.
- Hypernova is a persistent service; it doesn't die after every request like PHP does.  That means that intra-request caching is a thing (and, in fact, the only way it achieves acceptable perf levels).
- Turns out that the majority of your time in a naive react rendering service is not spent rendering to string - it's spent _requiring modules_.  Therefore having some sort of module cache (like hypernova has) is absolutely vital.  v8js has no such facility.
- For v8js, the interplay between php and js data was pretty sketchy when I looked at it.  I managed to segfault PHP frequently.  This may have changed in the intervening years.
- The v8 engine, in general, is good at optimizing code it has to run over and over.  If you have a long-running process (hypernova) it benefits from this.  php-v8js does not share environment between php requests, so you're running "cold" each time.

I'm probably forgetting some stuff.  Hope that helps.

**Comment by doeixd** [comment]
Hey, why don't you just use Next.js?

**Comment by aftabnaveed** [comment]
Thanks @roippi  for the detailed answer after playing and trying Hypernova I can now  clear  say that it is a better solution than phpv8js which we are currently using.  Hypernova technically is an in memory solution and it has Batchmanager for rendering multiple components in parallel which PHPv8JS does not provide. 

I am now just wondering how can I re-hydrate my components on the client side?  When I include the client javascript bundle it basically re-initialises the page.
